/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as InscricoesRouteImport } from './routes/inscricoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CourseBuilderRouteImport } from './routes/course-builder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as InscricaoRefRouteImport } from './routes/inscricao.$ref'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CertificateCodeRouteImport } from './routes/certificate.$code'
import { Route as CoursesCourseIdEnrollRouteImport } from './routes/courses.$courseId.enroll'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricoesRoute = InscricoesRouteImport.update({
  id: '/inscricoes',
  path: '/inscricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseBuilderRoute = CourseBuilderRouteImport.update({
  id: '/course-builder',
  path: '/course-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRefRoute = InscricaoRefRouteImport.update({
  id: '/inscricao/$ref',
  path: '/inscricao/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateCodeRoute = CertificateCodeRouteImport.update({
  id: '/certificate/$code',
  path: '/certificate/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdEnrollRoute = CoursesCourseIdEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/course-builder': typeof CourseBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/inscricoes': typeof InscricoesRoute
  '/instructor': typeof InstructorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/inscricao/$ref': typeof InscricaoRefRoute
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseId/enroll': typeof CoursesCourseIdEnrollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/course-builder': typeof CourseBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/inscricoes': typeof InscricoesRoute
  '/instructor': typeof InstructorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/inscricao/$ref': typeof InscricaoRefRoute
  '/courses': typeof CoursesIndexRoute
  '/courses/$courseId/enroll': typeof CoursesCourseIdEnrollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/course-builder': typeof CourseBuilderRoute
  '/dashboard': typeof DashboardRoute
  '/inscricoes': typeof InscricoesRoute
  '/instructor': typeof InstructorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/inscricao/$ref': typeof InscricaoRefRoute
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseId/enroll': typeof CoursesCourseIdEnrollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/course-builder'
    | '/dashboard'
    | '/inscricoes'
    | '/instructor'
    | '/sitemap.xml'
    | '/certificate/$code'
    | '/courses/$courseId'
    | '/inscricao/$ref'
    | '/courses/'
    | '/courses/$courseId/enroll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/course-builder'
    | '/dashboard'
    | '/inscricoes'
    | '/instructor'
    | '/sitemap.xml'
    | '/certificate/$code'
    | '/courses/$courseId'
    | '/inscricao/$ref'
    | '/courses'
    | '/courses/$courseId/enroll'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/course-builder'
    | '/dashboard'
    | '/inscricoes'
    | '/instructor'
    | '/sitemap.xml'
    | '/certificate/$code'
    | '/courses/$courseId'
    | '/inscricao/$ref'
    | '/courses/'
    | '/courses/$courseId/enroll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CourseBuilderRoute: typeof CourseBuilderRoute
  DashboardRoute: typeof DashboardRoute
  InscricoesRoute: typeof InscricoesRoute
  InstructorRoute: typeof InstructorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CertificateCodeRoute: typeof CertificateCodeRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
  InscricaoRefRoute: typeof InscricaoRefRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricoes': {
      id: '/inscricoes'
      path: '/inscricoes'
      fullPath: '/inscricoes'
      preLoaderRoute: typeof InscricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-builder': {
      id: '/course-builder'
      path: '/course-builder'
      fullPath: '/course-builder'
      preLoaderRoute: typeof CourseBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$ref': {
      id: '/inscricao/$ref'
      path: '/inscricao/$ref'
      fullPath: '/inscricao/$ref'
      preLoaderRoute: typeof InscricaoRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$code': {
      id: '/certificate/$code'
      path: '/certificate/$code'
      fullPath: '/certificate/$code'
      preLoaderRoute: typeof CertificateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/enroll': {
      id: '/courses/$courseId/enroll'
      path: '/enroll'
      fullPath: '/courses/$courseId/enroll'
      preLoaderRoute: typeof CoursesCourseIdEnrollRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
  }
}

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdEnrollRoute: typeof CoursesCourseIdEnrollRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdEnrollRoute: CoursesCourseIdEnrollRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CourseBuilderRoute: CourseBuilderRoute,
  DashboardRoute: DashboardRoute,
  InscricoesRoute: InscricoesRoute,
  InstructorRoute: InstructorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CertificateCodeRoute: CertificateCodeRoute,
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
  InscricaoRefRoute: InscricaoRefRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
